name: Phocial Marketing
favicon: null
layout_spectrum: 0.2746911491267383
typography_spectrum: 0.8905299266334623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.11850434588268399
  lightness: 0.7955954617355019
  saturation: 0.579107225406915
  rhythmicContrast: 0.4200466061010957
purpose: []
